### ISSUE TITLE
Faulty link to Jobs page on Tonies.com

### ISSUE THREAD

**Issue by theold190** [boxine/bx_py_utils#169]
It seems that the link to the career page in README.md is not working anymore. I get a 404 error when I open https://tonies.com/jobs/. Maybe it should be replaced with https://tonies.com/de-de/jobs-en/?

My nephews love Toniebox and listen to stories in their every car trip. Your product is fantastic, you do great job!

**Comment by flbraun** [comment]
Hi @theold190, thanks for the report!
I have passed this on to our People & Culture team, they're in charge of the jobs website. I'll let you know when they fixed it.

**Comment by jedie** [comment]
the redirect works, so this can be closed ;)

**Comment by theold190** [comment]
Thanks for checking the issue. I guess the problem is with the locale used in the browser. In my case when I click https://tonies.com/jobs/ I get redirected to https://tonies.com/en-eu/jobs/ And that page shows a 404 error as in an attached image 
![Screenshot_20241029_135346_Chrome](https://github.com/user-attachments/assets/9653c52a-25d0-44ae-adb4-cd3eafd5e290)

**Comment by phihag** [comment]
Looks like we urgently need to hire a programmer who can handle out these different-region issues, just for our jobs page! ;)

**Comment by phihag** [comment]
We will fix the redirect, so the URL can remain as is.
Thanks for reporting @theold190 !
