### ISSUE TITLE
github actions: test with different django versions

### ISSUE THREAD

**Issue by jedie** [boxine/bx_py_utils#28]
IMHO we test currently only with the latest django version.

**Comment by Chiron1991** [comment]
I think this ticket can be closed? According to the tox configuration we have a matrix of Python 3.6-3.9 and Django 2.2, 3.0 and 3.1.

**Comment by jedie** [comment]
Yes, fixed via https://github.com/boxine/bx_py_utils/commit/bd7864cd030bacbf7d5cbce602222a5609412b8f#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711
